url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Pedro Beirão" # the name of your site, e.g. ACME Corp.

# TODO want to add flags
# TODO would it be possible to have 2 images in each project in the home page
# TODO add tags to html

links:
  - link: https://github.com/
    user: Pedro-Beirao
    icon: github.svg
  - name: linkedin
    link: https://linkedin.com/in/
    user: pedro-beirão-694386175
    icon: linkedin.svg

collections:
  blog:
    output: true
    permalink: /blog/:name/

projects:
  - name: dsda-launcher
    desc: A launcher GUI for dsda-doom
    link: /blog/dsda-launcher
    role: Author
    tags: [doom, ui]

  - name: dsda-doom # TODO want to add the actual logo
    desc: One of the most important modern Doom source ports
    link: /blog/dsda-doom
    role: Maintainer
    tags: [doom, rendering]

  - name: dsdarchive
    desc: Website that hosts Doom's speedrunning scene
    link: /blog/dsdarchive
    role: Maintainer
    tags: [doom, website]

  - name: pyopenglDoom
    desc: Doom renderer using PyOpenGL. An exercise on the anatomy of .wad
    link: https://github.com/Pedro-Beirao/pyopenglDoom
    role: Author
    tags: [doom, rendering]

  - name: mindcuber-python
    desc: A program that solves a Rubik's cube with a ev3 Mindstorms, without needing a SD card
    link: /blog/mindcuber-python
    role: Author
    tags: [robot]

  - name: Jet Set Billy
    desc: A recreation of the cult classic game for the ZX Spectrum, Jet Set Willy
    link: https://github.com/Pedro-Beirao/Jet-Set-Billy
    role: Author
    tags: [game]

  - name: My Name is Jeff
    desc: A game about two Robot brothers that take on challenges together
    link: https://ec1ipse03.itch.io/mynameisjeff
    role: Author
    tags: [game, godot]

  - name: Void Pursuit
    desc: 2D spaceship shooting game
    link: https://github.com/Pedro-Beirao/Void-Pursuit
    role: Author
    tags: [game, unity]

  - name: Non Stop Dude
    desc: Retro style platformer where you can't stop running
    link: https://pedrobeirao.itch.io/nonstopdude
    role: Author
    tags: [game, unity]

  - name: ICL Discord Bot
    desc: Hosted in the official SuperbossGames Discord server, this is the bot that handles intruder competitive tournaments
    link: https://github.com/Pedro-Beirao/icl-discord-bot
    role: Author
    tags: [intruder, bot]

  - name: Balloon Race
    desc: ThreeJS experimentation scene of a two player balloon race
    link: https://github.com/Pedro-Beirao/threejs-projects/tree/master/tp3 # TODO update repo
    role: Author
    tags: [rendering]

  - name: IGN Search Engine
    desc: A search engine (with semantic search capabilities) for the IGN review database
    link: https://github.com/Pedro-Beirao/pri # TODO update repo
    role: Author
    tags: []

  - name: esnake
    desc: Project that aims to port the classic Snake game to many platforms for learning purposes
    link: https://github.com/Pedro-Beirao/esnake
    role: Author
    tags: [learn] # TODO i dont like this tag

  - name: Blinq
    desc: 2 player board game where the objective is to connect both side of your color/symbol, written in prolog
    link: https://github.com/Pedro-Beirao/FEUP_PFL_2023_24
    role: Author
    tags: []

  - name: Blockade
    desc: Blockade running in an Arduino with a graphics display
    link: https://www.youtube.com/watch?v=ZYB3jM4idB0
    role: Author
    tags: [game] # TODO i dont like this tag, maybe the same as robot?

  - name: Intruder Map Recovery
    desc: Scripts and tools to recover Intruder maps made with older Unity versions, and port them to make them playable again
    link:
    role: Author
    tags: [intruder]

  - name: dsda related scripts
    desc: Some scripts I made to be distributed to be used in dsda related purposes, as well as the one off builds
    link:
    role: Author
    tags: [doom]

  - name: Unity Playground
    desc: My personal playground project to test/show Unity stuff
    link:
    role: Author
    tags: [unity]

  - name: FAIR
    desc: FAIRification of a Comercial Aircraft Accidents dataset
    link:
    role: Author
    tags: []

  - name: LLM Quantization
    desc: A comprehensive research project evaluating the impact of quantization on LLM energy consumption and performance
    link:
    role: Author
    tags: [ai]

  - name: Thesis
    desc: Building an editor for the IEC-61499 standard
    link:
    role: Author
    tags: [website]

  - name: Other OSS
    desc: I would like to find a way to include some open source projects I've contributed to, tbf it's mostly Doom related :P
    link:
    role: Contributor
    tags: []

  # - name:
  #   desc:
  #   link:
  #   role: Author
  #   tags: []
